micronaut:
  application:
    name: kafka-manager
  server:
    port: 8080
  heartbeat:
    enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

swagger-ui.enabled: true
